version: '3'

services:
  orr:
    image: mmisw/orr:3.9.6
    container_name: orr
    restart: always
    shm_size: 2g

    depends_on:
      - agraph
      - mongo

    ports:
      - "${ORR_HOST_PORT}:8080"

    volumes:
      - ${HOST_CONFIG_DIR}:/etc/orront
      - ${ORR_HOST_DATA}:/opt/orr-ont-base-directory

    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=90.0

      - MONGO_HOST=mongo
      - MONGO_PORT=27017

      - AGRAPH_HOST=agraph
      - AGRAPH_PORT=10035

  agraph:
    image: franzinc/agraph:v6.1.1
    container_name: agraph
    restart: always
    shm_size: 2g

    ports:
      - "${AGRAPH_HOST_PORT}:10035"

    volumes:
      - ${ORR_HOST_DATA}:/opt/orr-ont-base-directory

  mongo:
    image: mongo:3.4.2
    container_name: mongo
    restart: always

    ports:
      - "${MONGO_HOST_PORT}:27017"

    volumes:
      - ${MONGO_HOST_DATA}:/data/db
